In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [11]:
print('1D ARRAY')
a = np.array([1,2,3,4,5])
print(a)
print(a.size)
print(a.shape)

1D ARRAY
[1 2 3 4 5]
5
(5,)


In [12]:
print('2D ARRAY')
b = np.array([[1,2,3,4,5],
            [6,7,8,9,10]])
print(b)
print(b.size)
print(b.shape)

2D ARRAY
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
(2, 5)


In [14]:
print('3D ARRAY')
c = np.array([[1,2,3,4,5],
            [6,7,8,9,10],[11,12,13,14,15]])
print(c)
print(c.size)
print(c.shape)

3D ARRAY
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
15
(3, 5)


In [16]:
print(type(c))
print(a.dtype)
print(b.dtype)
print(c.dtype)

<class 'numpy.ndarray'>
int64
int64
int64


In [21]:
arr = np.array([[1,2,3,4,5],
            [6,7,8,9,10],[11,12,13,14,15]])
print(arr)
arr1 = arr.transpose()
print(arr1)
print(arr.shape)
print(arr1.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
(3, 5)
(5, 3)


In [22]:
# np.empty((rows,cols),dtype)

np.empty((4,4), dtype= int)

array([[23925768161198147, 32370111954616435, 30962681235308636,
        30399748463132788],
       [30681274977550368, 12948244073152609, 32651616996819049,
        25896170311057512],
       [28710924373327984, 26740556586287209, 27303510834217060,
        25896196080664693],
       [32651591226556520, 12948368627204207, 29555336418492531,
        33495715508715636]])

In [29]:
# np.ones((rows,cols),dtype)
# np.zeros((rows,cols),dtype)

arr =  np.ones((1,6),dtype = int)
arr

array([[1, 1, 1, 1, 1, 1]])

In [28]:
arr =  np.ones((3,6),dtype = int)
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [30]:
# np.arange(start,end,step)

a = np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [33]:
# .reshape((rows,cols))

a = a.reshape(3,3)
b = a
print(b)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [40]:
# .flatten() -copy of original array

c = b.flatten()
print(c)

[ 2  4  6  8 10 12 14 16 18]


In [41]:
# .ravel() - refernce of original array

b.ravel()

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
#array slicing

arr = np.arange(1,51)
arr = arr.reshape(10,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [45]:
print(arr[0])
print(arr[2])
print(arr[0,3])

[1 2 3 4 5]
[11 12 13 14 15]
4


In [59]:
print(arr[: ,2])
print()
print(arr[2:4, 4])
print()
print(arr[2:4 , 2:4])

[ 3  8 13 18 23 28 33 38 43 48]

[15 20]

[[13 14]
 [18 19]]


In [65]:
arr1 = np.arange(1,19).reshape((6,3))
arr2 = np.arange(19,37).reshape((6,3))
print(arr1)
print(arr2)
print(arr1+ arr2)
np.add(arr1,arr2)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]]
[[20 22 24]
 [26 28 30]
 [32 34 36]
 [38 40 42]
 [44 46 48]
 [50 52 54]]


array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [66]:
arr2 = arr2.reshape((3,6))
print(arr1)
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [67]:
arr1@arr2

array([[ 162,  168,  174,  180,  186,  192],
       [ 387,  402,  417,  432,  447,  462],
       [ 612,  636,  660,  684,  708,  732],
       [ 837,  870,  903,  936,  969, 1002],
       [1062, 1104, 1146, 1188, 1230, 1272],
       [1287, 1338, 1389, 1440, 1491, 1542]])

In [72]:
print(arr2.max()) #value
print(arr2.argmax()) #index


36
17


In [73]:
val1 = np.sum(arr1)
val2 = np.sum(arr2)
print(val1)
print(val2)

171
495


In [75]:
# 1 = rows
val1 = np.sum(arr1, axis = 1)
val2 = np.sum(arr2, axis = 1)
print(val1)
print(val2)

[ 6 15 24 33 42 51]
[129 165 201]


In [76]:
# 0 = cols
val1 = np.sum(arr1, axis = 0)
val2 = np.sum(arr2, axis = 0)
print(val1)
print(val2)

[51 57 63]
[75 78 81 84 87 90]


In [78]:
print(np.mean(arr1))
print(np.mean(arr2))
print()
print(np.std(arr1))
print(np.std(arr2))

9.5
27.5

5.188127472091127
5.188127472091127
