In [16]:
#07-04-2025
#sqlwithpython(mysql)
#mysqlandtkinter

In [2]:
pip install mysql-connector-python

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
from mysql import connector

connection = connector.connect(user = "root" , password = "admin", host = "localhost", db = "salesDB")

In [4]:
from mysql import connector

connection = connector.connect(user = "root" , password = "admin", host = "localhost", db = "salesDB")

cursor = connection.cursor()
cursor.execute("show tables")
tables = cursor.fetchall()

for table in tables:
    print(table)

('customers',)
('orderdetails',)
('orders',)
('products',)


In [14]:
from mysql import connector

connection = connector.connect(user = "root" , password = "admin", host = "localhost", db = "salesDB")

cursor = connection.cursor()
cursor.execute("select * from customers")
records = cursor.fetchall()

for i in records:
    print(i)

(1, 'John', 'Doe', 'john.doe@example.com', '123-456-7890', '123 Main St')
(2, 'Jane', 'Smith', 'jane.smith@example.com', '987-654-3210', '456 Elm St')
(3, 'Alice', 'Johnson', 'alice.johnson@example.com', '111-222-3333', '789 Oak St')
(4, 'Bob', 'Brown', 'bob.brown@example.com', '444-555-6666', '101 Pine St')
(5, 'Charlie', 'Davis', 'charlie.davis@example.com', '555-666-7777', '202 Birch St')
(6, 'Diana', 'Miller', 'diana.miller@example.com', '666-777-8888', '303 Cedar St')
(7, 'Eve', 'Wilson', 'eve.wilson@example.com', '777-888-9999', '404 Maple St')
(8, 'Frank', 'Taylor', 'frank.taylor@example.com', '888-999-0000', '505 Willow St')
(9, 'Grace', 'Moore', 'grace.moore@example.com', '999-000-1111', '606 Palm St')
(10, 'Harry', 'Anderson', 'harry.anderson@example.com', '111-000-2222', '707 Redwood St')
(11, 'Sam', 'Prasad', 'sam@gmail.com', '943-234-1080', '123 sub St')
(12, 'Thiru', 'Lok', 'Thiru@gmail.com', '987-897-1090', '106,mettukuppam Road')


In [8]:
from mysql import connector

connection = connector.connect(user = "root" , password = "admin", host = "localhost", db = "salesDB")

cursor = connection.cursor()
cursor.execute("insert into customers(first_name, last_name, email, phone, address) values('Sam','Prasad', 'sam@gmail.com','943-234-1080','123 sub St')")

connection.commit()

In [15]:
import tkinter as tk
from tkinter import messagebox
import mysql.connector

def connect_db():
    try:
        conn = mysql.connector.connect(
            user = "root" , 
            password = "admin", 
            host = "localhost", 
            db = "salesDB"
        )
        return conn
    except mysql.connector.Error as e:
        messagebox.showerror("Database Error", f"Error Connecting to the database: \n{e}")
        return None

 
def insert_values():
    first_name = entry_fname.get()
    last_name = entry_lname.get()
    email = entry_email.get()
    phone = entry_phone.get()
    address = entry_address.get()
    
    if first_name and last_name and email and phone and address:
        conn = connect_db()
        if conn:
            cursor = conn.cursor()
            cursor.execute("INSERT INTO customers(first_name, last_name, email, phone, address) VALUES (%s, %s, %s, %s, %s)", 
                           (first_name, last_name, email, phone, address))
            conn.commit()
            cursor.close()
            conn.close()
            messagebox.showinfo("Success", "Values added successfully!")
            clear_entries()
            fetch_values()
    else:
        messagebox.showwarning("Input Error", "Please enter all fields!")

def fetch_values():
    conn = connect_db()
    if conn:
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM customers")
        rows = cursor.fetchall()
        cursor.close()
        conn.close()

        listbox_jobs.delete(0, tk.END)  
        for row in rows:
            listbox_jobs.insert(tk.END, f"First_Name: {row[0]} | Last_Name: {row[1]} | Email: {row[2]} | Phone: {row[3]} | Address: {row[4]}")


def clear_entries():
    entry_fname.delete(0, tk.END)
    entry_lname.delete(0, tk.END)
    entry_email.delete(0, tk.END)
    entry_phone.delete(0, tk.END)
    entry_address.delete(0, tk.END)


root = tk.Tk()
root.title("Database Management GUI")
root.geometry("450x500")

tk.Label(root, text="First_Name:").pack()
entry_fname = tk.Entry(root)
entry_fname.pack()

tk.Label(root, text="Last_Name:").pack()
entry_lname = tk.Entry(root)
entry_lname.pack()

tk.Label(root, text="Email:").pack()
entry_email = tk.Entry(root)
entry_email.pack()

tk.Label(root, text="Phone:").pack()
entry_phone = tk.Entry(root)
entry_phone.pack()

tk.Label(root, text="Address:").pack()
entry_address = tk.Entry(root)
entry_address.pack()

tk.Button(root, text="Add Values", command=insert_values).pack(pady=5)

tk.Label(root, text="Values List:").pack()
listbox_jobs = tk.Listbox(root, width=70, height=10)
listbox_jobs.pack()

tk.Button(root, text="Refresh List", command=fetch_values).pack(pady=5)


fetch_values()

root.mainloop()


        

In [ ]:
# 08-04-2025

#dateandtime 
# threading

In [1]:
from datetime import datetime

now = datetime.now()

now

datetime.datetime(2025, 4, 9, 18, 44, 26, 864427)

In [2]:
now.year

2025

In [3]:
now.month

4

In [4]:
now.day

9

In [8]:
now.strftime("the year %y month %m date %d")

'the year 25 month 04 date 09'

In [9]:
now.strftime("%A")

'Wednesday'

In [10]:
now.strftime("%B")

'April'

In [12]:
from datetime import date

date1 = date(2024,12,12)
date2 = date(2025,4,9)

date2-date1

datetime.timedelta(days=118)

In [14]:
date = datetime(2025,4,12)

date.strftime("%A")

'Saturday'

In [23]:
#adding days to a date

from datetime import timedelta

today = datetime.today()

upcoming90 = timedelta(days =90)

today+upcoming90

datetime.datetime(2025, 7, 8, 18, 51, 56, 679139)

In [24]:
import time

lt = time.localtime()
lt.tm_year

2025

In [29]:
lt.tm_mon

4

In [30]:
time.strftime("%H: %M: %S")

'18: 54: 33'

In [ ]:
time.strftime("%H: %M: %S", lt)

In [34]:
obj = time.time()
obj

1744205216.9187362

In [35]:
print(time.ctime(obj))

Wed Apr  9 18:56:56 2025


In [38]:
#digital clock

import time

while True:
    laptop_time = time.localtime()

    print(time.strftime("%H: %M: %S",laptop_time))
    time.sleep(3)
    break

19: 01: 18


In [39]:
#calculating the execution time of a program

st = time.time()

for i in range(100000000):
    pass

et = time.time()

print(et - st)

3.5316574573516846


In [41]:
def student_count():
    for i in range(10):
        print("Student number is ",i)
        time.sleep(1)
def student_mark():
    for i in range(300,400, 10):
        print("Student mark is ",i)
        time.sleep(1)
student_count()
student_mark()

Student number is  0
Student number is  1
Student number is  2
Student number is  3
Student number is  4
Student number is  5
Student number is  6
Student number is  7
Student number is  8
Student number is  9
Student mark is  300
Student mark is  310
Student mark is  320
Student mark is  330
Student mark is  340
Student mark is  350
Student mark is  360
Student mark is  370
Student mark is  380
Student mark is  390


In [53]:
import threading

st = time.time()

def student_count():
    for i in range(10):
        print("Student number is ",i)
        time.sleep(1)
def student_mark():
    for i in range(300,400, 10):
        print("Student mark is ",i)
        time.sleep(1) 
        
t1 = threading.Thread(target = student_count)
t2 = threading.Thread(target = student_mark)



t1.start() 
t2.start()
t1.join()
t2.join()


et = time.time()
print(et - st)



Student number is  0
Student mark is  300
Student number is  1
Student mark is  310
Student mark is Student number is  2
 320
Student mark is Student number is  3
 330
Student number is  4
Student mark is  340
Student number is Student mark is  350
 5
Student mark is  360
Student number is  6
Student mark is  370
Student number is  7
Student number is Student mark is  380
 8
Student number is Student mark is  390
 9
10.017608404159546


In [ ]:
#09-04-2025
#regularexpressionmodule

In [2]:
import re

txt = "python is interpretted and dynamic programming language and also platform independent"

print(re.findall("^python", txt))

['python']


In [5]:
import re

txt = "python is interpretted and dynamic programming language and also platform independent"

print(re.findall("independent$", txt))

['independent']


In [6]:
import re

txt = "python is interpretted and dynamic programming language and also platform independent"

print(re.findall("and*", txt))

['and', 'an', 'and']


In [11]:
import re

txt = "python is interpretted and dynamic programming language and also platform independent"

print(re.findall("et{2}", txt))

['ett']


In [12]:
import re

txt = "python is interpretted and dynamic programming language and also platform independent"

print(re.findall("and.*", txt))

['and dynamic programming language and also platform independent']


In [13]:
import re

txt = "python is interpretted and dynamic programming language and also platform independent"

print(re.findall("[a-f]", txt))

['e', 'e', 'e', 'd', 'a', 'd', 'd', 'a', 'c', 'a', 'a', 'a', 'e', 'a', 'd', 'a', 'a', 'f', 'd', 'e', 'e', 'd', 'e']


In [14]:
import re

txt = "1.python is interpretted and dynamic programming language and also 2.platform independent"

print(re.findall("[0-9]", txt))

['1', '2']


In [19]:
import re

txt = "11:00 am is best time to sleep and 5:00 am - 6:00 am is to wake up"

print(re.findall("[0-9]*[:][0-9]*", txt))

['11:00', '5:00', '6:00']


In [22]:
import re

txt = "11:00 am is best time to sleep and 5:00 am - 6:00 am is to wake up"

print(re.search("sleep", txt).span())

(25, 30)


In [25]:
import re

txt = "11:00 am is best time to sleep and 5:00 am - 6:00 am is to wake up"

print(re.split(r"\bt\w*", txt))

['11:00 am is best ', ' ', ' sleep and 5:00 am - 6:00 am is ', ' wake up']


In [26]:
import re

txt = "11:00 am is best time to sleep and 5:00 am - 6:00 am is to wake up"

ans = re.split(r"\bt\w*", txt)

ans

['11:00 am is best ', ' ', ' sleep and 5:00 am - 6:00 am is ', ' wake up']

In [29]:
import re

txt = "11:00 am is best time to sleep and 5:00 am - 6:00 am is to wake up"

print(re.findall(r"\bt\w*", txt))

['time', 'to', 'to']


In [30]:

txt = "11:00 am is best time to sleep and 5:00 am - 6:00 am is to wake up"

print(re.split("\s", txt))

['11:00', 'am', 'is', 'best', 'time', 'to', 'sleep', 'and', '5:00', 'am', '-', '6:00', 'am', 'is', 'to', 'wake', 'up']


<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Senthil Kumar\AppData\Local\Temp\ipykernel_14932\2246038935.py:3: SyntaxWarning: invalid escape sequence '\s'
  print(re.split("\s", txt))


In [32]:

txt = "11:00 am is best time to sleep and 5:00 am - 6:00 am is to wake up"

print(re.split(" ", txt))

['11:00', 'am', 'is', 'best', 'time', 'to', 'sleep', 'and', '5:00', 'am', '-', '6:00', 'am', 'is', 'to', 'wake', 'up']


In [33]:

txt = "11:00 am is best time to sleep and 5:00 am - 6:00 am is to wake up"

print(re.sub("wake","woke", txt))

11:00 am is best time to sleep and 5:00 am - 6:00 am is to woke up


In [ ]:
#10-04-2025
# numpy library
#basicsofnumpy

In [1]:
import numpy as np

arr1 = np.array([3,2,8,9])

type(arr1)

numpy.ndarray

In [2]:
arr1.ndim

1

In [3]:
arr1.shape

(4,)

In [6]:
arr1 = np.array([[3,2],[8,9]])
type(arr1)

numpy.ndarray

In [7]:
arr1

array([[3, 2],
       [8, 9]])

In [8]:
arr1.ndim

2

In [9]:
arr1.shape

(2, 2)

In [10]:
arr1[1,0]

np.int64(8)

In [11]:
arr1.dtype

dtype('int64')

In [12]:
arr2 = np.array([[4,2,3],[5,1,8]])
arr2

array([[4, 2, 3],
       [5, 1, 8]])

In [13]:
arr2[1,1]

np.int64(1)

In [14]:
arr1

array([[3, 2],
       [8, 9]])

In [15]:
arr1[:, 1]

array([2, 9])

In [16]:
arr1[0,:]

array([3, 2])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
np.zeros((2,2,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [20]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
np.full((3,2,2),9)

array([[[9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9]]])

In [22]:
np.random.rand(3,2)

array([[0.272525  , 0.03823202],
       [0.70077174, 0.28554128],
       [0.56392152, 0.09563421]])

In [24]:
arr2 = np.random.randint(5,30, size=[3,4])
arr2

array([[16, 26, 27, 15],
       [15, 18, 11, 19],
       [ 8, 29, 18, 28]], dtype=int32)

In [25]:
arr3 = np.random.randint(5,30,size = [2,3,3])
arr3

array([[[18,  5, 18],
        [22, 10, 18],
        [ 8, 23,  8]],

       [[10, 26, 20],
        [18, 26, 19],
        [18, 10, 19]]], dtype=int32)

In [26]:
arr2

array([[16, 26, 27, 15],
       [15, 18, 11, 19],
       [ 8, 29, 18, 28]], dtype=int32)

In [27]:
arr2 = arr3.reshape(3,6)
arr2

array([[18,  5, 18, 22, 10, 18],
       [ 8, 23,  8, 10, 26, 20],
       [18, 26, 19, 18, 10, 19]], dtype=int32)

In [28]:
arr4 = np.random.randint(5,30, size = (2,3))
arr5 = np.random.randint(5,30, size = (2,3))
arr4

array([[24, 22, 28],
       [26, 29, 15]], dtype=int32)

In [29]:
arr5

array([[16, 24,  6],
       [18, 18, 22]], dtype=int32)

In [31]:
np.vstack([arr4,arr5])

array([[24, 22, 28],
       [26, 29, 15],
       [16, 24,  6],
       [18, 18, 22]], dtype=int32)

In [32]:
np.hstack([arr4,arr5])

array([[24, 22, 28, 16, 24,  6],
       [26, 29, 15, 18, 18, 22]], dtype=int32)

In [ ]:
#11-04-2025
#pandas

In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd

print(pd.__doc__)


pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and

In [3]:
import pandas as pd

l1 = [4,2,6,7]
s1 = pd.Series(l1)
s1

0    4
1    2
2    6
3    7
dtype: int64

In [4]:
print(s1.dtype)
print(s1.shape)
print(s1[3])

int64
(4,)
7


In [6]:
print(s1.min())

2


In [7]:
print(s1.max())

7


In [8]:
print(s1.sum())

19


In [9]:
import pandas as pd

d1 = {"apple" : 34}
s1 = pd.Series(d1)
s1

apple    34
dtype: int64

In [10]:
import pandas as pd 

d1 = {"apple":34,"banana":5, "cherry":9}
s1 = pd.Series(d1)
s1

apple     34
banana     5
cherry     9
dtype: int64

In [12]:
data = {"apple": [34,23,12], "banana" : [5,3,8], "cherry":[9,8,6]}

df = pd.DataFrame(data)
df

apple  banana  cherry
0     34       5       9
1     23       3       8
2     12       8       6

In [13]:
df["cherry"]

0    9
1    8
2    6
Name: cherry, dtype: int64

In [14]:
df.iloc[1]

apple     23
banana     3
cherry     8
Name: 1, dtype: int64

In [9]:
import pandas as pd
df = pd.read_csv("employee.csv")
df

name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4     NaN  3000.0  NaN  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female

In [11]:
df1 = df.dropna()
df1

name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
5    john  3000.0  4.0  losvegas   33  Female

In [3]:
df.head(2)

name  salary  exp      city  age  Gender
0  john  3000.0  4.0  losvegas   30    Male
1   doe  4000.0  5.0        dc   25  Female

In [4]:
df.tail(2)

name  salary  exp      city  age  Gender
6  evans     NaN  4.0  losvegas   31    Male
7    tom  3000.0  4.0       NaN   37  Female

In [5]:
df.shape

(8, 6)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    7 non-null      object 
 1   salary  7 non-null      float64
 2   exp     7 non-null      float64
 3   city    7 non-null      object 
 4   age     8 non-null      int64  
 5   Gender  8 non-null      object 
dtypes: float64(2), int64(1), object(3)
memory usage: 516.0+ bytes


In [8]:
df = pd.read_json("example.json")
df

name  age      city new_user
name  John   30  New York    Alice
age   John   30  New York       25

In [16]:
import pandas as pd

df2 = pd.read_csv("employee.csv")
df2.dropna(inplace= True)
df2

name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
5    john  3000.0  4.0  losvegas   33  Female

In [17]:
import pandas as pd

df3 = pd.read_csv("employee.csv")
df3.fillna("unknown", inplace=True)
df3

C:\Users\Senthil Kumar\AppData\Local\Temp\ipykernel_17572\1471433983.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df3.fillna("unknown", inplace=True)


name   salary      exp      city  age  Gender
0     john   3000.0      4.0  losvegas   30    Male
1      doe   4000.0      5.0        dc   25  Female
2   robert   8000.0      6.0     paris   27    Male
3    chris   9000.0      7.0   newyork   24  Female
4  unknown   3000.0  unknown  losvegas   35    Male
5     john   3000.0      4.0  losvegas   33  Female
6    evans  unknown      4.0  losvegas   31    Male
7      tom   3000.0      4.0   unknown   37  Female

In [20]:
import pandas as pd

df3 = pd.read_csv("employee.csv")
df3["name"].fillna("unknown", inplace=True)
df3

C:\Users\Senthil Kumar\AppData\Local\Temp\ipykernel_17572\765815886.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3["name"].fillna("unknown", inplace=True)


name  salary  exp      city  age  Gender
0     john  3000.0  4.0  losvegas   30    Male
1      doe  4000.0  5.0        dc   25  Female
2   robert  8000.0  6.0     paris   27    Male
3    chris  9000.0  7.0   newyork   24  Female
4  unknown  3000.0  NaN  losvegas   35    Male
5     john  3000.0  4.0  losvegas   33  Female
6    evans     NaN  4.0  losvegas   31    Male
7      tom  3000.0  4.0       NaN   37  Female

In [ ]:
# vedio 28.40 11-04-2025